### ISSUE TITLE
[Epic] Support schema updates

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1002]
Currently schemas can only be created, never updated or deleted. We need to allow this mutation, and we need a mechanic (Lens) to handle version differences between nodes.

This epic has been converted to an almanac form available here: https://source.almanac.io/docs/N2o87ZyxzsruNHSlAErwHMVnqNBPOZFn

Watch out for time-traveling queries and absolutely ensure that they are tested.

WARNING: The P2P system will break in its current form if collections are allowed to be renamed, see discussion in discord thread [dev-db/Collection vs Schema](https://discord.com/channels/427944769851752448/1063181018074452019) (search for "The second thing is related to the schema ID. The P2P system uses").

Children (very roughly ordered in descending order of todo):

### Tasks
- [ ] https://github.com/sourcenetwork/defradb/issues/1013
- [ ] https://github.com/sourcenetwork/defradb/issues/1014
- [ ] https://github.com/sourcenetwork/defradb/issues/1022
- [ ] https://github.com/sourcenetwork/defradb/issues/1023
- [ ] https://github.com/sourcenetwork/defradb/issues/1006
- [ ] https://github.com/sourcenetwork/defradb/issues/1008
- [ ] https://github.com/sourcenetwork/defradb/issues/1015
- [ ] https://github.com/sourcenetwork/defradb/issues/1004
- [ ] https://github.com/sourcenetwork/defradb/issues/1181
- [ ] https://github.com/sourcenetwork/defradb/issues/1208
- [ ] https://github.com/sourcenetwork/defradb/issues/1220
- [ ] https://github.com/sourcenetwork/defradb/issues/1209
- [ ] https://github.com/sourcenetwork/defradb/issues/1747
- [ ] https://github.com/sourcenetwork/defradb/issues/1771
- [ ] https://github.com/sourcenetwork/defradb/issues/1772
- [ ] https://github.com/sourcenetwork/defradb/issues/1773
- [ ] https://github.com/sourcenetwork/defradb/issues/1774
- [ ] https://github.com/sourcenetwork/defradb/issues/1775
- [ ] https://github.com/sourcenetwork/defradb/issues/1169
- [ ] https://github.com/sourcenetwork/defradb/issues/1007
- [x] https://github.com/sourcenetwork/defradb/issues/1003
- [ ] https://github.com/sourcenetwork/defradb/issues/1005
- [ ] https://github.com/sourcenetwork/defradb/issues/1009
- [ ] https://github.com/sourcenetwork/defradb/issues/1010
- [x] https://github.com/sourcenetwork/defradb/issues/1011
- [ ] https://github.com/sourcenetwork/defradb/issues/1012
- [x] https://github.com/sourcenetwork/defradb/issues/1024
- [ ] https://github.com/sourcenetwork/defradb/issues/1448
- [ ] https://github.com/sourcenetwork/defradb/issues/1556
- [ ] https://github.com/sourcenetwork/defradb/issues/1590
- [ ] https://github.com/sourcenetwork/defradb/issues/1589
- [ ] https://github.com/sourcenetwork/defradb/issues/1591
- [ ] https://github.com/sourcenetwork/defradb/issues/1592
- [ ] https://github.com/lens-vm/lens/issues/46
- [ ] https://github.com/sourcenetwork/defradb/issues/1596
- [x] https://github.com/sourcenetwork/defradb/issues/1597
- [ ] https://github.com/sourcenetwork/defradb/issues/1598
- [ ] https://github.com/sourcenetwork/defradb/issues/1601
- [ ] https://github.com/sourcenetwork/defradb/issues/1640
- [ ] https://github.com/sourcenetwork/defradb/issues/1648
- [ ] https://github.com/sourcenetwork/defradb/issues/1649
- [ ] https://github.com/sourcenetwork/defradb/issues/1719
- [ ] https://github.com/sourcenetwork/defradb/issues/1884
- [ ] https://github.com/sourcenetwork/defradb/issues/1885
- [ ] https://github.com/sourcenetwork/defradb/issues/1886
- [ ] https://github.com/sourcenetwork/defradb/issues/2255
- [ ] https://github.com/sourcenetwork/defradb/issues/2287

Loosely related:
- https://github.com/sourcenetwork/defradb/issues/1016
- https://github.com/sourcenetwork/defradb/issues/1025
- https://github.com/sourcenetwork/defradb/issues/1027
- https://github.com/sourcenetwork/defradb/issues/985
- https://github.com/sourcenetwork/defradb/issues/1386
- https://github.com/sourcenetwork/defradb/issues/1385
