### ISSUE TITLE
[EPIC] Head Exchange

### ISSUE THREAD

**Issue by jsimnz** [sourcenetwork/defradb#1275]
Currently we don't *proactively* exchange heads between peers.

If a peer receives a new head, it will traverse the DAG and resolve all missing blocks. However, if a peer makes a local update offline, comes online, receives an update from another peer, it won't sync the change of its current document with the peer who just sent it the update.

So the first peer would have both updates, and the second peer would only have its own change.

This also goes towards the RPC api for the p2p system to actually implement the HeadRequest endpoint.
```[tasklist]
### Tasks
- [ ] https://github.com/sourcenetwork/defradb/issues/3062
- [ ] https://github.com/sourcenetwork/defradb/issues/3063
- [ ] https://github.com/sourcenetwork/defradb/issues/3064
```
