### ISSUE TITLE
[Epic] Test DefraDB

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1508]
This issue hosts stuff we think we would like to have in order to be satisfied with the correctness of DefraDB at the time of release 1.0.0. The stuff listed here is highly dynamic and I would encourage people to add items regardless of how thought-out they might be.  Once we are fairly certain that we do want a thing for/before 1.0.0 that thing should be in issue or SIP format, otherwise inline/plain-text is good enough. 

```[tasklist]
### Tasks
- [ ] https://github.com/sourcenetwork/docs.source.network/issues/112
- [ ] +95% line code coverage
- [ ] #324 
- [ ] #73 
- [ ] #197 (issue currently includes benchmarking and cross-platform testing)
- [ ] Basic fuzz testing
- [ ] Random GQL Request testing, maybe using https://github.com/IBM/graphql-query-generator maybe coupled with randomized schema
- [ ] Long-life testing, ensuring DefraDB doesn't fall over after X hours/days/etc
- [ ] Some kind of large-scale randomized P2P resilience testing (chaos monkey-like?)
- [ ] Some kind of chaos monkey-like datastore testing, ensuring very bad things dont happen when unexpected file-system stuff happens 
```

**Comment by shahzadlone** [comment]
Was just browsing @fredcarle @AndrewSisley, and I see a lot of sub-tasks on this required for v1 issue that raise some eyebrows if we really will be able to realistically achieve them all before v1. For example 95% line code coverage and some others? Is this something that was discussed recently?

**Comment by AndrewSisley** [comment]
> Is this something that was discussed recently?

No this is a couple of years old, and we haven't really decided what we actually want for v1 IMO.
