### ISSUE TITLE
[EPIC] Integration of ACP

### ISSUE THREAD

**Issue by fredcarle** [sourcenetwork/defradb#1738]
This epic tracks the list of tasks related to integrating the ACP into DefraDB.

After initial implementation lands, here are the next steps:

1) The following features currently are not allowed or don't work (these can be worked on by the team in a parallel manner):
- https://github.com/sourcenetwork/defradb/issues/2366
- [x] [Adding Secondary Indexes](https://github.com/sourcenetwork/defradb/issues/2365)
- [ ] [Backing/Restoring Private Documents](https://github.com/sourcenetwork/defradb/issues/2430)

Note: The above `(1)` features don't require to expand or tinker with the ACP interface defined in the `./acp` package at all. When adding tests don't forget to add a use case example to the README in the `./acp` folder.

2) The following features may have undefined/unstable behavior and should be assumed to not be working until proper testing is added for them, so add testing for these:
- [ ] [Views](https://github.com/sourcenetwork/defradb/issues/2018)
- [x] [Average Operations](https://github.com/sourcenetwork/defradb/issues/2475)
- [x] [Count Operations](https://github.com/sourcenetwork/defradb/issues/2474)
- [ ] [Group Operations](https://github.com/sourcenetwork/defradb/issues/2473)
- [ ] [Limit Operations](https://github.com/sourcenetwork/defradb/issues/2472)
- [ ] [Order Operations](https://github.com/sourcenetwork/defradb/issues/2471)
- [ ] [Sum Operations](https://github.com/sourcenetwork/defradb/issues/2470)
- [ ] [Dag/Commit Operations](https://github.com/sourcenetwork/defradb/issues/2469)
- [ ] [Delete With Filter Operations](https://github.com/sourcenetwork/defradb/issues/2468
- [ ] [Update With Filter Operations](https://github.com/sourcenetwork/defradb/issues/2467)
- [ ] [Type Join Many Operations](https://github.com/sourcenetwork/defradb/issues/2466)
- [ ] [Type Join One Operations](https://github.com/sourcenetwork/defradb/issues/2466)
- [ ] [Parallel Operations](https://github.com/sourcenetwork/defradb/issues/2465)
- [ ] [Execute Explain](https://github.com/sourcenetwork/defradb/issues/2464)

Note: The above `(2)` features likely might just need to add tests, when adding tests don't forget to add a use case example to the README in the `./acp` folder.

3) Somewhat requires ACP/Sourcehub/Identity Knowledge, better to pick above issues if they are available by most devs:
- [Migrate to Source Identity Prefix & Validate](https://github.com/sourcenetwork/defradb/issues/2358)
- [Generate Identity](https://github.com/sourcenetwork/defradb/issues/2554)
- [Full Auth Identity](https://github.com/sourcenetwork/defradb/issues/2017)
- [Show/Dump Previously Uploaded Policy](https://github.com/sourcenetwork/defradb/issues/2388)
- [Configure Auth Identity](https://github.com/sourcenetwork/defradb/issues/2416)
- [Async Doc Register & Registering Queue](https://github.com/sourcenetwork/defradb/issues/2360)
- [x] #2762
- #2905
- #2906 

Future features:
- [ ] [Permissioned Schema Migration Requests](https://github.com/sourcenetwork/defradb/issues/2230)
- [ ] #2640
- [ ] #3238
- [ ] [Use AAC to Turn Off ACP](https://github.com/sourcenetwork/defradb/issues/2271)

Resolved:
- [x] [Inject Identity In Ctx](https://github.com/sourcenetwork/defradb/issues/2439)
- [x] [Move Identity flag higher up & Inherit the flag in sub commands](https://github.com/sourcenetwork/defradb/issues/2438)

**Comment by shahzadlone** [comment]
Since v0 NAC is now completed (#2640) so closed that issue so putting the stuff we need to consolidate here.

Admin Operation Access Control for operations that are only for admins.

In Initial Planning we said to gate these operations:
- Turn on / off DAC ACP, shareability: https://github.com/sourcenetwork/defradb/issues/2271
- Schema patch
- Other schema stuff: https://github.com/sourcenetwork/defradb/issues/2230
- Collection Description
- Node identity
- Put server dump command under AAC (https://github.com/sourcenetwork/defradb/pull/2633#discussion_r1608797380)
- Maybe use with views as well

However as we progressed we decided that it might be better to blanket ban/wrap every node operation under the acp system with one permission that grants access to all of them for know until we implement more granular permissions and operation control later.

## Plan / Sub-tasks:

- [x] Reorganize exist document acp stuff and rename terminology to make it clean to implement AAC (1/2) (https://github.com/sourcenetwork/defradb/issues/3656)

- [x] Reorganize exist document acp stuff and rename terminology to make it clean to implement AAC (2/2) (https://github.com/sourcenetwork/defradb/issues/3751)

- #3669
- #3875
- #3878
- #3876
- #3877


- https://github.com/sourcenetwork/defradb/issues/3590
- Do: #3718 After above bump is done.

- [ ] Ability to by-pass DAC for admin-identity
- [ ] Ability to by-pass DAC for shared admin access.

- [ ] Add the feature to disable/enable Document ACP and then also gating those 2 operations with AAC (#2271)

- [ ] Make DAC only purge command
- [ ] Make NAC only purge command
- [ ] Empty Target inconsistency https://github.com/sourcenetwork/defradb/issues/3796

- [ ] Make the node operation access more granular with permissions.

- [ ] https://github.com/sourcenetwork/defradb/issues/3866
- [ ] https://github.com/sourcenetwork/defradb/issues/3836

- [ ] Making the document register call async

- [ ] https://github.com/sourcenetwork/defradb/issues/3882

** Roughly discussed on V1 planning call to have the features above before V1 **

- [ ] Test DAC combination with other features that have test gap but work (known tech debt)
- [ ] Support DAC in combination with other features that dont work (example: `backup <> DAC` - also priority from petestic) 
- [ ] NAC: Dump current NAC policy in use
- [ ] DAC: Dump target policy that was uploaded
- [ ] Dynamic NAC Policy Generation (less hard-coded than now)
- [ ] Ability to take custom NAC policy to dictate node access control on start.

Extra util nice to haves:
- [ ] DAC: Unregister a target doc
- [ ] DAC: Register all docs of a collection
- [ ] DAC: Unregister all docs of a collection
- [ ] DAC: Guided DAC Policy Writer
- [ ] NAC: Guided NAC Policy Writer



Standup Notes:
- Since disabling the document ACP is a new feature, wait to do it after first version of AAC is done to make the scope of PRs consumable.
- Everyone was happy with a blanket approach for now, they understand the aac sharing capability will temporarily be a bit odd as it will be giving full-access and not a specific one.
