### ISSUE TITLE
[Epic] Consistent GQL Renaming

### ISSUE THREAD

**Issue by shahzadlone** [sourcenetwork/defradb#1750]
### Related SIP
This epic tracks progress of SIP-5: https://github.com/sourcenetwork/SIPs/pull/15/files

### Phase 1
- [x] Rename instances of `_key` to `_docID`
- [ ] Rename instances of `dockey(s)` and `id(s)` to `docID(s)`
- [ ] Rename related/foreign id instances from `<related>_id` to `_<related>ID`
- [ ] Rename other fields to be consistent in terms of capitalization
