### ISSUE TITLE
Restructure client.Description objects to correctly split Schema and Collections

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1911]
Proposed structure:
```
type CollectionDescription struct {
	Name string
	ID uint32
        GlobalID string // * ID to uniquely identify the collection on a network
	Description string // *
	SchemaVersionID string // **
	Fields []CollectionFieldDescription
	Indexes []IndexDescription
}
type CollectionFieldDescription struct {
	Name string
	ID FieldID // note: If all nodes are on exactly the same Defra version, this would be the same across all nodes, but it does not have to be - make sure this is documented
	Description string // *
	CollectionID uint32 // * for relations
	RelationName string // for relations
	RelationType RelationType // for relations, this type will be modified from the existing definition, it now only needs to say whether it is a one-one or a one-many
}
type SchemaDescription struct {
	SchemaID string
	Name string // note: this is just a label, // thought (from Fred/Keenan): This should probably not actually be defined here, and instead should be a local only thing, otherwise we increase the risk of clashes 
	VersionID string // thought (from Fred/Keenan):  This should probably just be `ID`, we could then rename this struct to `SchemaVersionDescription`
	VersionLabel string // *  // thought (from Fred/Keenan): This should probably not actually be defined here, and instead should be a local only thing, otherwise we increase the risk of clashes 
	Fields []SchemaFieldDescription
}
type SchemaFieldDescription struct {
	Name string
	Kind FieldKind
	CRDT CRDT // **
	SchemaID string // for relations
}
// * == new property
// ** == renamed
```
Additionally, `PatchSchema` will remain conceptually as-is, updating the schema object only - `PatchCollection` will be introduced to do the same for collection stuff.  `SetDefaultSchemaVersion` will be removed, as it's functionality will be covered by `PatchCollection`.

Worth noting perhaps is that a `SchemaFieldDescription` will only ever exist for the primary side of a relation.  `CollectionFieldDescription` will exist for both sides.

The pointer from CollectionDescription to SchemaDescription has been removed.  I think this makes the separation and [lack of] ownership clearer, as well as making stuff like PatchSchema/Collection more obvious to the user.  It may also force us to allow multiple collections from a single schema for free, as the data structure now demands it.

```[tasklist]
### Tasks
- [ ] https://github.com/sourcenetwork/defradb/issues/1886
- [ ] https://github.com/sourcenetwork/defradb/issues/1386
- [ ] https://github.com/sourcenetwork/defradb/issues/1385
- [ ] https://github.com/sourcenetwork/defradb/issues/1913
- [ ] https://github.com/sourcenetwork/defradb/issues/2004
```
