### ISSUE TITLE
Remove Schema from within CollectionDescription

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1913]
Replace `CollectionDescription.Schema` with `CollectionDescription.SchemaVersionID`.

This will require changing a large number (+100) of references, PatchSchema (and tests), and the serialization/ID logic.  Try and avoid changing anything else in this ticket. 
```[tasklist]
### Tasks
- [ ] https://github.com/sourcenetwork/defradb/issues/1955
- [ ] https://github.com/sourcenetwork/defradb/issues/1956
- [ ] https://github.com/sourcenetwork/defradb/issues/1958
- [ ] https://github.com/sourcenetwork/defradb/issues/1963
- [ ] https://github.com/sourcenetwork/defradb/issues/1964
```
