### ISSUE TITLE
[EPIC] Config refactor

### ISSUE THREAD

**Issue by nasdf** [sourcenetwork/defradb#2257]
The config package is difficult to maintain at the moment and can be improved in a few areas.

- Decouple the config from the consumer packages (net, http, etc.)
- Validation and parsing should be handled by the consumers of the config values.
- Remove config items that are not used or not relevant.
- Merge config into cli package. (The cli is the only place where the config is used.)

```[tasklist]
### Tasks
- [ ] https://github.com/sourcenetwork/defradb/issues/2263
- [ ] https://github.com/sourcenetwork/defradb/issues/2277
- [ ] https://github.com/sourcenetwork/defradb/issues/2295
```
