### ISSUE TITLE
[Epic] Network abstraction

### ISSUE THREAD

**Issue by nasdf** [sourcenetwork/defradb#2553]
This issue is for tracking the overall progress of creating a network abstraction.

- [ ] Replace gRPC with custom `libp2p` protocol
- [ ] Move block processing logic to `db` package
- [ ] Refactor block fetching with `boxo` fetcher
- [ ] Replace `db` dependency in `net` package with events
- [ ] Create JavaScript network implementation
