### ISSUE TITLE
[Epic] CLI overhaul v0.3

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#271]
v0.3.0
- [x] #258 
- [x] https://github.com/sourcenetwork/defradb/issues/340
- [x] https://github.com/sourcenetwork/defradb/issues/347
- [x] https://github.com/sourcenetwork/defradb/issues/348
- [x] https://github.com/sourcenetwork/defradb/issues/350
- [x] #577 
- [x] ensure pipeline works well
- [x] https://github.com/sourcenetwork/defradb/issues/349
- [x] https://github.com/sourcenetwork/defradb/issues/613
- [x] regenerate in-repo documentation
- [x] short ref for license information
- [x] all texts pretty
