### ISSUE TITLE
[Epic] Restructure data store keys

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#310]
Decided in https://github.com/sourcenetwork/defradb/issues/306

- [x] [Remove PrimaryKey from scan path](https://github.com/sourcenetwork/defradb/issues/311)
- [x] [Remove IndexId from path](https://github.com/sourcenetwork/defradb/issues/312)
- [x] [Move InstanceType from tail to earlier element](https://github.com/sourcenetwork/defradb/issues/313)
