### ISSUE TITLE
[Epic] Explain Request Functionality

### ISSUE THREAD

**Issue by jsimnz** [sourcenetwork/defradb#35]
## Simple Explain SUB-TASKS (initial implementation will be `verbose = true`).
- [x] Explain `selectNode`
- [x] Explain `selectTopNode`
- [x] Explain `createNode`
- [x] Explain `deleteNode`
- #325 
- #474
- #477
- #478
- #475
- #483
- #481
- #482
- #479
- #597 
- #599 
- #525 
- #476
- #561
- #480
- #736
- #748
- #626 

## Debug Explain SUB-TASKS
- #948  

## Prediction Explain SUB-TASKS
- #327 

## Execution Explain SUB-TASKS
- #326 

## Bugs:
- #486
- #485
- #484

## CHECKLIST:
- [x] Update schema to parse in `@explain` directive from the `query` and `mutation` location only.
- [x] Iterate over all directive and find the matching `explain`.
- [ ] Introduce the option to set verbose false for explain request.
- [ ] Make sure to test MultiNode properly.

## DESCOPED:
- #361 
- #362
- #363 

## DESCRIPTION

Implement an `Explain` API + Endpoint for returning the structure of a plan graph as generated by the `planner` package. 

Request:
 ```
query @explain {
  user {
    _key
    age
    name
  }
}
```

 Response:
 ```
{
  "data": [
    {
      "explain": {
        "selectTopNode": {
          "selectNode": {
            "filter": null,
            "scanNode": {
              "collectionID": "1",
              "collectionName": "user",
              "filter": null
            }
          }
        }
      }
    }
  ]
}
```

There should be additional data options. Such as `ANALYZE` (from SQL) which would actually execute the Request, and provide insights into perf analysis on a per node basis and `EXECUTE` to provide insights to what was actually executed. 

There should be an additional option to change the verbosity level of explain to omit attributes like `filter` when they are `null`.

Output is only going to be in JSON.
