### ISSUE TITLE
[EPIC] CLI overhaul

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#647]
- [ ] builder pattern
- [x] https://github.com/sourcenetwork/defradb/issues/593
- [ ] schema commands
- [ ] config commands
- [x] https://github.com/sourcenetwork/defradb/issues/351
- [ ] "framework providing hook for command cancelation"
- [x] https://github.com/sourcenetwork/defradb/issues/354
- [ ] https://github.com/sourcenetwork/defradb/issues/461
- [x] https://github.com/sourcenetwork/defradb/issues/353
- [x] https://github.com/sourcenetwork/defradb/issues/587
- [x] https://github.com/sourcenetwork/defradb/issues/352

**Comment by fredcarle** [comment]
Stale
