### ISSUE TITLE
[Epic] Refactor: Logging system

### ISSUE THREAD

**Issue by jsimnz** [sourcenetwork/defradb#67]
Need to review the entire logging workflow/implementation for the database. Currently use a few randomly initialized global scoped loggers on various packages. 

We should define a single logger instance during DB initialization, and propogate that logger to all the sub components. This can be propogated using the new `context` arguments everywhere.

Child issues:
- [x] https://github.com/sourcenetwork/defradb/issues/218
- [x] https://github.com/sourcenetwork/defradb/issues/233
- [x] https://github.com/sourcenetwork/defradb/issues/235
- [x] https://github.com/sourcenetwork/defradb/issues/237
- [x] https://github.com/sourcenetwork/defradb/issues/239
- [x] https://github.com/sourcenetwork/defradb/issues/242
- [x] https://github.com/sourcenetwork/defradb/issues/243
- [x] https://github.com/sourcenetwork/defradb/issues/245
- [x] https://github.com/sourcenetwork/defradb/issues/247
- [x] https://github.com/sourcenetwork/defradb/issues/249
- [x] https://github.com/sourcenetwork/defradb/issues/260
